/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ragnaros.client;

import java.awt.Graphics;
import java.awt.Graphics2D;
import ragnaros.client.gui.*;
import ragnaros.game.Card;

/**
 *
 * @author Carl
 */
public class PanCard extends javax.swing.JPanel{

    public PanCard(){
        initComponents();
        setOpaque(false);
        cardDisplay.setIsFront(true);
    }
    private Card card;
    private CardDisplay cardDisplay = new CardDisplay(null);
    
    public void setCard(Card card){
        this.card = card;
        cardDisplay.setCard(card);
        updateUI();
    }

    
    @Override
    protected void paintComponent(Graphics _graphics){
        super.paintComponent(_graphics);
        if(card != null){
            Graphics2D graphics = (Graphics2D) _graphics;
            graphics.scale((getWidth() / 300.0), (getHeight() / 400.0));
            PanField.drawCardDisplay(graphics, this, cardDisplay);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
